# Generated by Django 4.2.7 on 2025-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='cnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.FileField(max_length=50, upload_to='')),
                ('lname', models.FileField(max_length=50, upload_to='')),
                ('email', models.EmailField(max_length=50)),
                ('message', models.FileField(max_length=50, upload_to='')),
            ],
        ),
    ]
