# Generated by Django 5.0.4 on 2025-08-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Exclusive', 'Exclusive')], default='General', max_length=20),
        ),
    ]
